import { describe, expect, it } from 'vitest'
import {
  applyGerberExportProfile,
  getNormalizedDrillFileName,
  getNormalizedGerberFileName,
} from './exportProfiles.ts'
import type { GerberTextEntry } from './types.ts'

const ALTIUM_ENTRY: GerberTextEntry = {
  name: 'board.GBL',
  type: 'bottom-copper',
  content: `G04*
G04 #@! TF.GenerationSoftware,Altium Limited,Altium Designer,20.0.13 (296)*
G04*
G04 Layer_Color=16711680*
%FSLAX24Y24*%
%MOIN*%`,
}

const EASYEDA_MM_ENTRY: GerberTextEntry = {
  name: 'board.G1',
  type: 'inner-layer',
  content: `G04 Layer: InnerLayer1*
G04 EasyEDA Pro v2.2.40.3, 2025-07-26 21:37:14*
G04 Gerber Generator version 0.3*
G04 Scale: 100 percent, Rotated: No, Reflected: No*
G04 Dimensions in millimeters*
G04 Leading zeros omitted, absolute positions, 4 integers and 5 decimals*
G04 Generated by one-click*
%FSLAX45Y45*%
%MOMM*%`,
}

describe('getNormalizedGerberFileName', () => {
  it('输出立创风格层文件名', () => {
    expect(getNormalizedGerberFileName('board.GTL', 'top-copper')).toBe('Gerber_TopLayer.GTL')
    expect(getNormalizedGerberFileName('board.GBO', 'bottom-silkscreen')).toBe(
      'Gerber_BottomSilkscreenLayer.GBO',
    )
    expect(getNormalizedGerberFileName('board.G2', 'inner-layer')).toBe(
      'Gerber_InnerLayer2.G2',
    )
  })

  it('输出立创风格钻孔文件名', () => {
    expect(getNormalizedDrillFileName('plated')).toBe('Drill_PTH_Through.DRL')
    expect(getNormalizedDrillFileName('non-plated')).toBe('Drill_NPTH_Through.DRL')
    expect(getNormalizedDrillFileName('via')).toBe('Drill_PTH_Through_Via.DRL')
  })
})

describe('applyGerberExportProfile', () => {
  it('将英制文件标准化为立创风格头部', () => {
    const result = applyGerberExportProfile(
      ALTIUM_ENTRY.content,
      ALTIUM_ENTRY,
      new Date(2026, 3, 8, 12, 0, 0),
    )

    expect(result).toContain('G04 Layer: BottomLayer*')
    expect(result).toContain('G04 EasyEDA Pro v3.2.58, 2026-04-08 12:00:00*')
    expect(result).toContain('G04 Generated by one-click*')
    expect(result).not.toContain('Altium Designer')
    expect(result).not.toContain('G04 Dimensions in millimeters*')
    expect(result).toContain('%FSLAX24Y24*%')
  })

  it('保留毫米格式所需的头部说明', () => {
    const result = applyGerberExportProfile(
      EASYEDA_MM_ENTRY.content,
      EASYEDA_MM_ENTRY,
      new Date(2026, 3, 8, 12, 0, 0),
    )

    expect(result).toBe(EASYEDA_MM_ENTRY.content)
  })
})
