import { formatDateTime } from '../../shared/utils/format.ts'
import { normalizeLineEndings } from '../../shared/utils/text.ts'
import { getInnerLayerOrder } from './fileTypes.ts'
import type { DrillFileRole, GerberTextEntry, KnownGerberFileType } from './types.ts'

const LEGACY_GENERATED_HEADER_PATTERNS = [
  /^G04 Layer: .+\*$/,
  /^G04 EasyEDA Pro .+\*$/,
  /^G04 Gerber Generator version .+\*$/,
  /^G04 Scale: .+\*$/,
  /^G04 Dimensions in millimeters\*$/,
  /^G04 Leading zeros omitted, absolute positions, 4 integers and 5 decimals\*$/,
  /^G04 Generated by one-click\*$/,
  /^G04 #@! TF\.GenerationSoftware,Altium Limited,Altium Designer,.+\*$/,
  /^G04 Layer_Physical_Order=\d+\*$/,
  /^G04 Layer_Color=\d+\*$/,
]

const LAYER_OUTPUT_NAMES: Record<Exclude<KnownGerberFileType, 'drill' | 'inner-layer'>, string> = {
  'top-copper': 'Gerber_TopLayer.GTL',
  'bottom-copper': 'Gerber_BottomLayer.GBL',
  'top-silkscreen': 'Gerber_TopSilkscreenLayer.GTO',
  'bottom-silkscreen': 'Gerber_BottomSilkscreenLayer.GBO',
  'top-mask': 'Gerber_TopSolderMaskLayer.GTS',
  'bottom-mask': 'Gerber_BottomSolderMaskLayer.GBS',
  'top-paste': 'Gerber_TopPasteMaskLayer.GTP',
  'bottom-paste': 'Gerber_BottomPasteMaskLayer.GBP',
  outline: 'Gerber_BoardOutlineLayer.GKO',
}

const DRILL_OUTPUT_NAMES: Record<DrillFileRole, string> = {
  plated: 'Drill_PTH_Through.DRL',
  'non-plated': 'Drill_NPTH_Through.DRL',
  via: 'Drill_PTH_Through_Via.DRL',
}

const HEADER_LAYER_NAMES: Record<Exclude<KnownGerberFileType, 'drill' | 'inner-layer'>, string> = {
  'top-copper': 'TopLayer',
  'bottom-copper': 'BottomLayer',
  'top-silkscreen': 'TopSilkscreenLayer',
  'bottom-silkscreen': 'BottomSilkscreenLayer',
  'top-mask': 'TopSolderMaskLayer',
  'bottom-mask': 'BottomSolderMaskLayer',
  'top-paste': 'TopPasteMaskLayer',
  'bottom-paste': 'BottomPasteMaskLayer',
  outline: 'BoardOutlineLayer',
}

function stripGeneratedHeaderLines(content: string): string {
  const lines = normalizeLineEndings(content).split('\n')
  let index = 0

  while (index < lines.length) {
    const line = lines[index] ?? ''
    if (line === 'G04*' || LEGACY_GENERATED_HEADER_PATTERNS.some((pattern) => pattern.test(line))) {
      index += 1
      continue
    }

    break
  }

  return lines.slice(index).join('\n')
}

function extractLeadingHeaderLines(content: string): string[] {
  const lines = normalizeLineEndings(content).split('\n')
  const headerLines: string[] = []

  for (const line of lines) {
    if (line === 'G04*' || line.startsWith('G04 ')) {
      headerLines.push(line)
      continue
    }

    break
  }

  return headerLines
}

function createGerberHeader(layerName: string, now: Date): string[] {
  return [
    `G04 Layer: ${layerName}*`,
    `G04 EasyEDA Pro v3.2.58, ${formatDateTime(now)}*`,
    'G04 Gerber Generator version 0.3*',
    'G04 Scale: 100 percent, Rotated: No, Reflected: No*',
  ]
}

export function getNormalizedGerberFileName(
  fileName: string,
  type: Exclude<KnownGerberFileType, 'drill'>,
): string {
  if (type === 'inner-layer') {
    const layerOrder = getInnerLayerOrder(fileName) ?? 1
    return `Gerber_InnerLayer${layerOrder}.G${layerOrder}`
  }

  return LAYER_OUTPUT_NAMES[type]
}

export function getNormalizedDrillFileName(role: DrillFileRole): string {
  return DRILL_OUTPUT_NAMES[role]
}

export function applyGerberExportProfile(
  content: string,
  entry: Pick<GerberTextEntry, 'name' | 'type'>,
  now: Date,
): string {
  const normalizedContent = normalizeLineEndings(content)
  const existingHeaderLines = extractLeadingHeaderLines(normalizedContent)
  const isEasyEdaSource = existingHeaderLines.some((line) => /^G04 EasyEDA Pro .+\*$/.test(line))

  if (isEasyEdaSource) {
    return normalizedContent
  }

  const body = stripGeneratedHeaderLines(content)
  const layerLabel =
    entry.type === 'inner-layer'
      ? `InnerLayer${getInnerLayerOrder(entry.name) ?? 1}`
      : HEADER_LAYER_NAMES[entry.type as Exclude<KnownGerberFileType, 'drill' | 'inner-layer'>]
  const header = createGerberHeader(layerLabel, now)
  const normalizedBody = normalizeLineEndings(body)

  if (/%MOMM\*%/i.test(normalizedBody)) {
    header.push('G04 Dimensions in millimeters*')
    header.push('G04 Leading zeros omitted, absolute positions, 4 integers and 5 decimals*')
  }

  header.push('G04 Generated by one-click*')

  return `${header.join('\n')}\n${normalizedBody}`
}
