import { formatDateTime } from '../../shared/utils/format.ts'
import { normalizeLineEndings } from '../../shared/utils/text.ts'
import { getLayerDisplayName } from './fileTypes.ts'
import type { KnownGerberFileType } from './types.ts'

export function injectEasyEdaHeader(
  content: string,
  fileName: string,
  type: Exclude<KnownGerberFileType, 'drill'>,
  now: Date,
): string {
  const normalized = normalizeLineEndings(content)

  if (normalized.includes('EasyEDA Pro')) {
    return normalized
  }

  const header = [
    `G04 Layer: ${getLayerDisplayName(fileName, type)}*`,
    `G04 EasyEDA Pro v3.2.91, ${formatDateTime(now)}*`,
    'G04 Gerber Generator version 0.3*',
    'G04 Scale: 100 percent, Rotated: No, Reflected: No*',
    'G04 Generated by one-click*',
  ]

  return `${header.join('\n')}\n${normalized}`
}
