import { formatDateTime } from '../../shared/utils/format.ts'
import { normalizeLineEndings } from '../../shared/utils/text.ts'

export function injectEasyEdaHeader(
  content: string,
  fileName: string,
  now: Date,
): string {
  const normalized = normalizeLineEndings(content)

  if (normalized.includes('EasyEDA Pro')) {
    return normalized
  }

  const layerName = fileName.split(/[\\/]/).pop() ?? fileName
  const header = [
    `G04 Layer: ${layerName}*`,
    `G04 EasyEDA Pro v3.2.91, ${formatDateTime(now)}*`,
    'G04 Gerber Generator version 0.3*',
    'G04 Scale: 100 percent, Rotated: No, Reflected: No*',
    'G04 Generated by one-click*',
  ]

  return `${header.join('\n')}\n${normalized}`
}
