import { describe, expect, it } from 'vitest'
import { decodeTextFile } from '../../shared/utils/text.ts'
import { zipArchive } from '../zip/zip.ts'
import { unzipArchive } from '../zip/unzip.ts'
import { generateGerberOutputs } from './processor.ts'

const TOP_SILK = `%FSLAX24Y24*%
%MOMM*%
%ADD10C,0.100*%
D10*
X001000Y002000D02*
X001500Y002500I000100J000200D01*
M02*`

const TOP_COPPER = `G04*
G04 #@! TF.GenerationSoftware,Altium Limited,Altium Designer,20.0.13 (296)*
G04*
G04 Layer_Color=255*
%FSLAX24Y24*%
%MOIN*%
%ADD10C,0.150*%
D10*
X010000Y010000D03*
M02*`

const EASYEDA_TOP_COPPER = `G04 Layer: TopLayer*
G04 EasyEDA Pro v3.2.131, 2026-05-06 23:14:15*
G04 Gerber Generator version 0.3*
G04 Scale: 100 percent, Rotated: No, Reflected: No*
G04 Dimensions in millimeters*
G04 Leading zeros omitted, absolute positions, 4 integers and 5 decimals*
G04 Generated by one-click*
%FSLAX45Y45*%
%MOMM*%
%ADD10C,0.2032*%
%ADD11C,1.20508*%
%ADD19C,1.5152*%
D10*
X010000Y010000D03*
M02*`

const INNER_LAYER = `%FSLAX45Y45*%
%MOMM*%
%ADD10C,0.2032*%
D10*
X000100Y000200D03*
M02*`

const OUTLINE = `%FSLAX45Y45*%
%MOMM*%
%ADD10C,0.2000*%
D10*
X000000Y000000D02*
X010000Y000000D01*
M02*`

const DRILL_PTH = `;TYPE=PLATED
;Layer: PTH_Through
M48
METRIC,LZ,0000.00000
T01C0.43180
%
G05
G90
T01
X1.47188Y-6.3499
M30`

const DRILL_NPTH = `;TYPE=NON_PLATED
;Layer: NPTH_Through
M48
METRIC,LZ,0000.00000
T01C1.00000
%
G05
G90
T01
X3.54118Y-9.39276
M30`

const DRILL_VIA = `;TYPE=PLATED
;Layer: PTH_Through_Via
M48
METRIC,LZ,0000.00000
T01C0.30500
%
G05
G90
T01
X7.112Y16.13395
M30`

const DRILL_SLOT = `;TYPE=PLATED
;Layer: PTH_Through
M48
METRIC,LZ,0000.00000
T05C0.5994
%
G90
G05
T05
G00X01517934Y00488044
M15
G01Y00494038
M16
M30`

function readEntryText(entries: ReturnType<typeof unzipArchive>, fileName: string): string {
  const entry = entries.find((item) => item.name === fileName)
  if (!entry) {
    throw new Error(`Missing entry: ${fileName}`)
  }

  return decodeTextFile(entry.data, fileName)
}

describe('generateGerberOutputs', () => {
  it('只输出标准制造文件并统一命名', () => {
    const progressMessages: string[] = []
    const archive = zipArchive([
      { name: 'Core_S3.GTO', data: new TextEncoder().encode(TOP_SILK) },
      { name: 'Core_S3.GTL', data: new TextEncoder().encode(TOP_COPPER) },
      { name: 'Core_S3.G1', data: new TextEncoder().encode(INNER_LAYER) },
      { name: 'Core_S3.GKO', data: new TextEncoder().encode(OUTLINE) },
      { name: 'Core_S3.GD1', data: new TextEncoder().encode('%FSLAX24Y24*%\nM02*') },
      { name: 'Core_S3.GM6', data: new TextEncoder().encode('%FSLAX24Y24*%\nM02*') },
      { name: 'Core_S3.TXT', data: new TextEncoder().encode(DRILL_PTH) },
      { name: 'Core_S3-NPTH.XLN', data: new TextEncoder().encode(DRILL_NPTH) },
      { name: 'Core_S3-Via.TXT', data: new TextEncoder().encode(DRILL_VIA) },
      { name: 'CAMtastic1.Cam', data: new TextEncoder().encode('skip me') },
      { name: 'FlyingProbeTesting.json', data: new TextEncoder().encode('{}') },
    ])

    const outputs = generateGerberOutputs({
      archive,
      count: 1,
      now: new Date(2026, 3, 8, 12, 0, 0),
      seed: 42,
      sourceName: 'board.zip',
      onProgress(progress) {
        progressMessages.push(progress.message)
      },
    })

    expect(outputs).toHaveLength(1)
    expect(outputs[0]?.fileName).toBe('board_改1.zip')

    const resultArchive = unzipArchive(outputs[0].data)
    expect(resultArchive.map((entry) => entry.name)).toEqual([
      'Gerber_TopLayer.GTL',
      'Gerber_InnerLayer1.G1',
      'Gerber_TopSilkscreenLayer.GTO',
      'Gerber_BoardOutlineLayer.GKO',
      'Drill_NPTH_Through.DRL',
      'Drill_PTH_Through.DRL',
      'Drill_PTH_Through_Via.DRL',
      'Core_S3.GD1',
      'Core_S3.GM6',
      'CAMtastic1.Cam',
      'FlyingProbeTesting.json',
    ])

    const copper = readEntryText(resultArchive, 'Gerber_TopLayer.GTL')
    const silkscreen = readEntryText(resultArchive, 'Gerber_TopSilkscreenLayer.GTO')
    const drill = readEntryText(resultArchive, 'Drill_PTH_Through.DRL')
    const gerberDoc = readEntryText(resultArchive, 'Core_S3.GD1')
    const mechanical = readEntryText(resultArchive, 'Core_S3.GM6')
    const camtastic = readEntryText(resultArchive, 'CAMtastic1.Cam')
    const flyingProbe = readEntryText(resultArchive, 'FlyingProbeTesting.json')

    expect(copper).toContain('G04 Layer: TopLayer*')
    expect(copper).toContain('G04 EasyEDA Pro v3.2.58, 2026-04-08 12:00:00*')
    expect(copper).not.toContain('Altium Designer')
    expect(copper).toMatch(/%ADD11C,0\.\d{4}\*%/)
    expect(progressMessages).toContain(
      '检测到原始 Gerber 由 Altium Designer 导出，结果产物将被伪装为立创 Gerber',
    )
    expect(silkscreen).toContain('G04 Layer: TopSilkscreenLayer*')
    expect(silkscreen).toContain('I000100J000200')
    expect(silkscreen).not.toContain('X001000Y002000D02*')
    expect(drill).toContain(';TYPE=PLATED')
    expect(drill).toContain('M48')
    expect(gerberDoc).toBe('%FSLAX24Y24*%\nM02*')
    expect(mechanical).toBe('%FSLAX24Y24*%\nM02*')
    expect(camtastic).toBe('skip me')
    expect(flyingProbe).toBe('{}')
  })

  it('兼容四层板输出与多钻孔文件命名', () => {
    const archive = zipArchive([
      { name: 'board.GTL', data: new TextEncoder().encode(TOP_COPPER) },
      { name: 'board.GBL', data: new TextEncoder().encode(TOP_COPPER) },
      { name: 'board.G2', data: new TextEncoder().encode(INNER_LAYER) },
      { name: 'board.G1', data: new TextEncoder().encode(INNER_LAYER) },
      { name: 'board.GTS', data: new TextEncoder().encode(OUTLINE) },
      { name: 'board.GBS', data: new TextEncoder().encode(OUTLINE) },
      { name: 'board.DRL', data: new TextEncoder().encode(DRILL_PTH) },
      { name: 'board_npth.TXT', data: new TextEncoder().encode(DRILL_NPTH) },
      { name: 'board_via.XLN', data: new TextEncoder().encode(DRILL_VIA) },
    ])

    const outputs = generateGerberOutputs({
      archive,
      count: 1,
      now: new Date(2026, 3, 8, 12, 0, 0),
      seed: 7,
      sourceName: '4layer.zip',
    })

    const resultArchive = unzipArchive(outputs[0].data)
    expect(outputs[0]?.fileName).toBe('4layer_改1.zip')
    expect(resultArchive.map((entry) => entry.name)).toContain('Gerber_InnerLayer1.G1')
    expect(resultArchive.map((entry) => entry.name)).toContain('Gerber_InnerLayer2.G2')
    expect(resultArchive.map((entry) => entry.name)).toContain('Gerber_BottomLayer.GBL')
    expect(resultArchive.map((entry) => entry.name)).toContain('Drill_NPTH_Through.DRL')
    expect(resultArchive.map((entry) => entry.name)).toContain('Drill_PTH_Through_Via.DRL')
    expect(resultArchive.map((entry) => entry.name)).not.toContain('FlyingProbeTesting.json')
  })

  it('将 GM1 外形层和拆分的圆孔槽孔合并输出', () => {
    const archive = zipArchive([
      { name: 'power.GTL', data: new TextEncoder().encode(TOP_COPPER) },
      { name: 'power.GM1', data: new TextEncoder().encode(OUTLINE) },
      { name: 'power-RoundHoles.TXT', data: new TextEncoder().encode(DRILL_PTH) },
      { name: 'power-SlotHoles.TXT', data: new TextEncoder().encode(DRILL_SLOT) },
    ])

    const outputs = generateGerberOutputs({
      archive,
      count: 1,
      now: new Date(2026, 4, 6, 22, 0, 0),
      seed: 11,
      sourceName: 'power.zip',
    })

    const resultArchive = unzipArchive(outputs[0].data)
    expect(outputs[0]?.fileName).toBe('power_改1.zip')
    expect(resultArchive.map((entry) => entry.name)).toContain('Gerber_BoardOutlineLayer.GKO')
    expect(resultArchive.map((entry) => entry.name)).toContain('Drill_PTH_Through.DRL')
    expect(resultArchive.map((entry) => entry.name)).not.toContain('Drill_PTH_Through_2.DRL')

    const outline = readEntryText(resultArchive, 'Gerber_BoardOutlineLayer.GKO')
    const drill = readEntryText(resultArchive, 'Drill_PTH_Through.DRL')

    expect(outline).toContain('G04 Layer: BoardOutlineLayer*')
    expect(drill).toContain('T01C0.43180')
    expect(drill).toContain('T05C0.5994')
    expect(drill).toContain('M15')
    expect(drill).toContain('G01Y00494038')
  })

  it('兼容新版 EasyEDA 标准命名与现有签名载体', () => {
    const archive = zipArchive([
      { name: 'Gerber_TopLayer.GTL', data: new TextEncoder().encode(EASYEDA_TOP_COPPER) },
      { name: 'Gerber_BottomLayer.GBL', data: new TextEncoder().encode(EASYEDA_TOP_COPPER) },
      { name: 'Gerber_TopSilkscreenLayer.GTO', data: new TextEncoder().encode(TOP_SILK) },
      { name: 'Gerber_BoardOutlineLayer.GKO', data: new TextEncoder().encode(OUTLINE) },
      { name: 'Drill_PTH_Through.DRL', data: new TextEncoder().encode(DRILL_PTH) },
      { name: 'Gerber_DocumentLayer.GDL', data: new TextEncoder().encode('document-layer') },
      { name: 'Gerber_DrillDrawingLayer.GDD', data: new TextEncoder().encode('drill-drawing-layer') },
    ])

    const outputs = generateGerberOutputs({
      archive,
      count: 1,
      now: new Date(2026, 4, 7, 10, 0, 0),
      seed: 17,
      sourceName: 'Gerber_XM_Power_Kit_2026-05-06.zip',
    })

    const resultArchive = unzipArchive(outputs[0].data)
    const copper = readEntryText(resultArchive, 'Gerber_TopLayer.GTL')
    const extraNames = resultArchive.map((entry) => entry.name)
    const documentLayer = readEntryText(resultArchive, 'Gerber_DocumentLayer.GDL')
    const drillDrawingLayer = readEntryText(resultArchive, 'Gerber_DrillDrawingLayer.GDD')

    expect(copper).toContain('G04 EasyEDA Pro v3.2.131, 2026-05-06 23:14:15*')
    expect(copper).toContain('%ADD19C,1.5152*%')
    expect(copper).toMatch(/%ADD20C,0\.\d{4}\*%/)
    expect(copper).not.toMatch(/%ADD21C,0\.\d{4}\*%/)
    expect(extraNames).toContain('Gerber_DocumentLayer.GDL')
    expect(extraNames).toContain('Gerber_DrillDrawingLayer.GDD')
    expect(documentLayer).toBe('document-layer')
    expect(drillDrawingLayer).toBe('drill-drawing-layer')
  })

  it('对没有有效 Gerber 文件的 ZIP 报错', () => {
    const archive = zipArchive([{ name: 'notes.txt', data: new TextEncoder().encode('no gerber') }])

    expect(() =>
      generateGerberOutputs({
        archive,
        count: 1,
        now: new Date(2026, 3, 8, 12, 0, 0),
        seed: 9,
        sourceName: 'notes.zip',
      }),
    ).toThrow('ZIP 中没有有效的 Gerber 文件。')
  })
})
